### PR TITLE
Fixed duplicates being created

### LINKED ISSUE #93: Prevent creation of duplicate applications
When creating an application it is possible to continuously create the same applcation

### PR DESCRIPTION
**Pull request by KieranHons**
Resolves #93

### CODE REVIEW

File: nucleus/src/main/java/za/co/absa/subatomic/infrastructure/pkg/view/jpa/PackageRepository.java [hunk 1]
```diff
@@ -15,5 +15,5 @@
 
     PackageEntity findByNameAndProjectProjectId(String name, String projectId);
 
-    List<PackageEntity> findByProjectId(Long projectId);
+    List<PackageEntity> findByProjectId(String projectId);
```
Comment (kbristow) [inline nucleus/src/main/java/za/co/absa/subatomic/infrastructure/pkg/view/jpa/PackageRepository.java]: Does this not need to be ProjectProjectId?

Comment (KieranHons) [reply nucleus/src/main/java/za/co/absa/subatomic/infrastructure/pkg/view/jpa/PackageRepository.java]: Oops, changing now
